<?php

namespace App\Services;

use App\Models\CompanyPaymentMethod;
use App\Models\Quotation;
use App\Models\SalesInvoice;
use Illuminate\Support\Facades\Storage;
use Mpdf\Mpdf;
use Mpdf\Output\Destination;

class B2bDocumentPdfService
{
    public function quotation(Quotation $quotation): string
    {
        $quotation->loadMissing(['company', 'branch', 'customer', 'creator', 'items', 'additionalCharges']);
        $paymentMethods = CompanyPaymentMethod::withoutGlobalScopes()
            ->where('company_id', $quotation->company_id)
            ->forDocument($quotation->document_type)
            ->get();
        $path = 'documents/'.$quotation->company_id.'/quotations/'.$quotation->quotation_number.'.pdf';
        $this->write('pdf.b2b-quotation', compact('quotation', 'paymentMethods'), $path, $quotation->quotation_number);

        return $path;
    }

    public function invoice(SalesInvoice $invoice): string
    {
        $invoice->loadMissing(['company', 'customer', 'quotation', 'sale.branch', 'sale.createdBy', 'sale.payments', 'sale.items.product', 'sale.additionalCharges']);
        $paymentMethods = CompanyPaymentMethod::withoutGlobalScopes()
            ->where('company_id', $invoice->company_id)
            ->forDocument('invoice')
            ->get();
        $path = 'documents/'.$invoice->company_id.'/invoices/'.$invoice->invoice_number.'.pdf';
        $this->write('pdf.b2b-sales-invoice', compact('invoice', 'paymentMethods'), $path, $invoice->invoice_number);

        return $path;
    }

    private function write(string $view, array $data, string $path, string $title): void
    {
        Storage::disk('local')->makeDirectory(dirname($path));
        Storage::disk('local')->makeDirectory('mpdf-temp');
        $pdf = new Mpdf(['tempDir' => Storage::disk('local')->path('mpdf-temp')]);
        $pdf->SetTitle($title);
        $pdf->SetAuthor('HARDEX');
        $pdf->SetHTMLFooter('<div style="font-size:8px;color:#64748b;text-align:center">Page {PAGENO} | Generated by HARDEX POS</div>');
        $pdf->WriteHTML(view($view, $data)->render());
        $pdf->Output(Storage::disk('local')->path($path), Destination::FILE);
    }
}
