<?php

namespace App\Services;

use Mpdf\Mpdf;

class PdfExportService
{
    public function generatePdf(string $reportTitle, array $payload): string
    {
        $mpdf = new Mpdf([
            'tempDir' => storage_path('app/mpdf'),
            'format' => 'A4-L',
            'margin_top' => 14,
            'margin_right' => 10,
            'margin_bottom' => 14,
            'margin_left' => 10,
        ]);

        $mpdf->SetHTMLFooter('<div style="font-size:9px; color:#4b5563; text-align:center;">Page {PAGENO} | Generated by HARDEX ERP</div>');
        $mpdf->WriteHTML(view('exports.pdf-report', [
            'title' => $reportTitle,
            ...$payload,
        ])->render());

        return $mpdf->Output('', 'S');
    }
}
