<?php

namespace App\Services;

use App\Models\Company;
use App\Models\WhatsAppRecipient;
use Carbon\CarbonInterface;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Storage;
use Mpdf\Mpdf;
use Mpdf\Output\Destination;

class WhatsAppStockAlertPdfService
{
    public function generate(Company $company, WhatsAppRecipient $recipient, CarbonInterface $generatedAt, Collection $rows, string $reference): string
    {
        $directory = 'whatsapp-reports/'.$company->id.'/'.$generatedAt->toDateString();
        Storage::disk('local')->makeDirectory($directory);
        Storage::disk('local')->makeDirectory('mpdf-temp');
        $relativePath = $directory.'/stock-alert-'.$reference.'-recipient-'.$recipient->id.'.pdf';
        $pdf = new Mpdf([
            'format' => 'A4-L',
            'tempDir' => Storage::disk('local')->path('mpdf-temp'),
        ]);
        $pdf->SetTitle('HARDEX Low / Out of Stock Report '.$generatedAt->toDateString());
        $pdf->SetAuthor('HARDEX');
        $pdf->SetHTMLFooter('<div style="font-size:8px;color:#64748b;text-align:center">Page {PAGENO} | Generated by HARDEX POS</div>');
        $scopeLabel = app(WhatsAppStockAlertService::class)->scopeLabel($company, $recipient);
        $pdf->WriteHTML(view('pdf.whatsapp-stock-alert', compact('company', 'recipient', 'generatedAt', 'rows', 'scopeLabel'))->render());
        $pdf->Output(Storage::disk('local')->path($relativePath), Destination::FILE);

        return $relativePath;
    }
}
