<?php

use App\Services\ProductionTraceabilityService;
use function Livewire\Volt\layout;
use function Livewire\Volt\mount;
use function Livewire\Volt\state;

layout('layouts.app'); state(['search' => '']);
mount(fn () => abort_unless(auth()->user()?->can('production.view_batch_traceability'), 403));
?>
<div class="space-y-5">
    <x-page-header title="Batch Traceability" description="Read-only production genealogy from immutable snapshots and inventory-ledger events." :breadcrumbs="['Dashboard'=>route('dashboard'),'Production'=>route('production.index'),'Reports'=>route('production.reports.index'),'Batch Traceability'=>null]" />
    <div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-navy-900"><label class="text-sm font-bold">Find a batch<input wire:model.live.debounce.400ms="search" placeholder="Batch, order, inspection, release reference or product…" class="mt-2 w-full rounded-xl border-slate-300 dark:border-slate-600 dark:bg-navy-950"></label><p class="mt-2 text-xs text-slate-500">Sales are matched only as potential downstream sales because sale items do not store a production batch or release ID.</p></div>
    @php($service = app(ProductionTraceabilityService::class))
    @php($batch = $service->find($search))
    @if($search !== '' && ! $batch)<div class="rounded-2xl border border-slate-200 bg-white p-12 text-center text-slate-500 dark:border-slate-700 dark:bg-navy-900">No accessible production batch matches this search.</div>@endif
    @if($batch)
        @php($order=$batch->productionOrder) @php($unit=$batch->product?->unit?->short_name)
        <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Batch',$batch->batch_number],['Product',($batch->product?->name ?: '—').' · '.($batch->product?->productFamily?->name ?: '—')],['Production Order',$order?->order_number],['Status',str($batch->resolvedStatus())->headline()]] as [$label,$value])<div class="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-navy-900"><p class="text-xs font-bold uppercase text-slate-500">{{ $label }}</p><p class="mt-1 font-black">{{ $value }}</p></div>@endforeach</div>
        <div class="grid gap-4 xl:grid-cols-2">
            <x-card><h2 class="text-lg font-black">Recipe, machine and assignment</h2><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><dt class="text-slate-500">Recipe snapshot</dt><dd>{{ $order?->snapshot?->recipe_name ?: 'Not captured' }} {{ $order?->snapshot?->recipe_version ? 'v'.$order->snapshot->recipe_version : '' }}</dd><dt class="text-slate-500">Snapshot captured</dt><dd>{{ $order?->snapshot?->captured_at?->format('d M Y H:i') ?: '—' }}</dd><dt class="text-slate-500">Machine</dt><dd>{{ $batch->machine?->name ?: '—' }}</dd><dt class="text-slate-500">Historical assigned mould</dt><dd>{{ $order?->assignment?->mould?->name ?: 'Not recorded' }}</dd><dt class="text-slate-500">Daily assignment</dt><dd>#{{ $order?->production_machine_assignment_id ?: '—' }} · {{ $order?->assignment?->production_date?->format('d M Y') ?: '—' }}</dd></dl></x-card>
            <x-card><h2 class="text-lg font-black">Production and curing</h2><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><dt class="text-slate-500">Planned / produced</dt><dd>{{ $order?->planned_quantity }} / {{ $order?->total_produced_quantity }} {{ $unit }}</dd><dt class="text-slate-500">Accepted / rejected</dt><dd>{{ $order?->accepted_quantity }} / {{ $order?->rejected_quantity }} {{ $unit }}</dd><dt class="text-slate-500">Released / remaining</dt><dd>{{ $batch->released_quantity }} / {{ $batch->remaining_quantity }} {{ $unit }}</dd><dt class="text-slate-500">Curing dates</dt><dd>{{ $batch->curing_started_at?->format('d M Y H:i') }} → {{ $batch->full_curing_at?->format('d M Y H:i') }}</dd></dl></x-card>
        </div>
        <x-card><h2 class="mb-3 text-lg font-black">Planned and actual material consumption</h2><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="p-2">Material</th><th class="p-2">Type</th><th class="p-2">Planned</th><th class="p-2">Actual</th>@can('production.view_cost_reports')<th class="p-2">Historical Unit Cost</th>@endcan</tr></thead><tbody>@forelse($order?->materials ?? [] as $m)<tr class="border-t dark:border-slate-700"><td class="p-2">{{ $m->materialProduct?->name ?: $m->name }}</td><td class="p-2">{{ str($m->line_type)->headline() }}</td><td class="p-2">{{ $m->planned_quantity }} {{ $m->unit?->short_name }}</td><td class="p-2">{{ $m->actual_quantity }} {{ $m->unit?->short_name }}</td>@can('production.view_cost_reports')<td class="p-2">{{ $m->unit_cost === null ? 'Cost unavailable' : 'TZS '.number_format((float)$m->unit_cost,2) }}</td>@endcan</tr>@empty<tr><td colspan="5" class="p-5 text-center text-slate-500">No material snapshots.</td></tr>@endforelse</tbody></table></div></x-card>
        <div class="grid gap-4 xl:grid-cols-2"><x-card><h2 class="mb-3 text-lg font-black">Curing actions and QC</h2><div class="space-y-3">@foreach($batch->actions as $a)<div class="rounded-lg bg-slate-50 p-3 dark:bg-navy-950"><b>{{ str($a->action_type)->headline() }}</b> · {{ $a->quantity ?: '—' }}<br><span class="text-xs text-slate-500">{{ $a->reason }} · {{ $a->created_at?->format('d M Y H:i') }}</span></div>@endforeach @foreach($batch->qualityInspections as $i)<div class="rounded-lg bg-slate-50 p-3 dark:bg-navy-950"><b>{{ $i->inspection_number }}</b> · {{ str($i->result)->headline() }} / {{ str($i->approval_status)->headline() }}<br><span class="text-xs text-slate-500">Inspector: {{ $i->inspector?->name ?: '—' }} · {{ $i->inspected_at?->format('d M Y H:i') }}</span></div>@endforeach @if($batch->actions->isEmpty() && $batch->qualityInspections->isEmpty())<p class="text-slate-500">No curing actions or inspections.</p>@endif</div></x-card>
        <x-card><h2 class="mb-3 text-lg font-black">Release events</h2><div class="space-y-3">@forelse($batch->releases as $r)<div class="rounded-lg bg-slate-50 p-3 dark:bg-navy-950"><b>{{ $r->release_number }}</b> · {{ $r->released_quantity }} {{ $unit }}<br><span class="text-xs text-slate-500">{{ $r->sourceLocation?->name }} → {{ $r->destinationLocation?->name }} · {{ $r->posting_reference }}</span></div>@empty<p class="text-slate-500">No release events.</p>@endforelse</div></x-card></div>
        @php($movements=$service->stockMovements($batch))
        <x-card><h2 class="mb-3 text-lg font-black">Inventory ledger</h2><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="p-2">Date</th><th class="p-2">Movement</th><th class="p-2">Quantity In</th><th class="p-2">Quantity Out</th><th class="p-2">Location / Reference</th></tr></thead><tbody>@forelse($movements as $m)<tr class="border-t dark:border-slate-700"><td class="p-2">{{ $m->movement_date?->format('d M Y H:i') }}</td><td class="p-2">{{ str($m->movement_type)->headline() }}</td><td class="p-2">{{ $m->quantity_in }}</td><td class="p-2">{{ $m->quantity_out }}</td><td class="p-2">{{ $m->stockLocation?->name ?: ($m->sourceLocation?->name.' → '.$m->destinationLocation?->name) }} · {{ $m->posting_reference }}</td></tr>@empty<tr><td colspan="5" class="p-5 text-center text-slate-500">No linked stock movements.</td></tr>@endforelse</tbody></table></div></x-card>
        @php($sales=$service->potentialSales($batch))
        <x-card><h2 class="text-lg font-black">Potential downstream sales from the same product/location</h2><p class="my-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-950/40 dark:text-amber-200">These are not guaranteed batch-specific sales. Current sale items identify product and location, but do not store the curing batch or release relationship.</p><div class="space-y-2">@forelse($sales as $item)<p class="text-sm"><b>{{ $item->sale?->sale_number }}</b> · {{ $item->base_quantity }} · {{ $item->stockLocation?->name }} · {{ $item->sale?->sale_date?->format('d M Y') }}</p>@empty<p class="text-sm text-slate-500">No potential downstream sales found.</p>@endforelse</div></x-card>
    @endif
</div>
