<?php
use App\Models\CustomerMaterialAccount;
use App\Services\CustomerMaterialAccountService;
use function Livewire\Volt\layout;
use function Livewire\Volt\mount;
use function Livewire\Volt\state;
layout('layouts.app');
state(['customerMaterialAccount','lines'=>[]]);
mount(function(CustomerMaterialAccount $customerMaterialAccount){$this->customerMaterialAccount=$customerMaterialAccount;$this->lines=$customerMaterialAccount->planLines->mapWithKeys(fn($line)=>[$line->id=>['planned_quantity'=>(float)$line->planned_quantity,'agreed_unit_price'=>(float)$line->agreed_unit_price,'amendment_reason'=>'']])->all();});
$saveLine=function(int $lineId,CustomerMaterialAccountService $service){$line=$this->customerMaterialAccount->planLines()->findOrFail($lineId);$row=$this->lines[$lineId];$this->validate(["lines.$lineId.planned_quantity"=>['required','numeric','gt:0'],"lines.$lineId.agreed_unit_price"=>['required','numeric','min:0'],"lines.$lineId.amendment_reason"=>['nullable','string','max:1000']]);$service->amendPlanLine($line,(float)$row['planned_quantity'],(float)$row['agreed_unit_price'],$row['amendment_reason']?:null,auth()->id());session()->flash('success','Plan line amended with an audit record.');};
?>
<div>
    @php $account=$customerMaterialAccount->fresh(['customer','planLines']); @endphp
    <x-page-header title="Edit Material Plan" :description="$account->reference_number.' · '.$account->project_name" :breadcrumbs="['Dashboard'=>route('dashboard'),'Material Accounts'=>route('customer-material-accounts.index'),$account->reference_number=>route('customer-material-accounts.show',$account),'Edit Plan'=>null]" />
    <x-alert type="warning" title="Historical safety">Product and unit snapshots cannot be replaced. Existing issues keep their original price and conversion. After any deposit or issue, every amendment requires a reason.</x-alert>
    <x-card class="mt-4"><x-table :headers="['Material / Unit','Already Issued','Planned Quantity','Agreed Unit Price','New Plan Value','Amendment Reason','']">@foreach($account->planLines as $line)<tr><td class="px-4 py-3 font-bold">{{ $line->product_name_snapshot }}<p class="text-xs font-normal text-slate-500">{{ $line->unit_name_snapshot }} · ×{{ $line->conversion_factor_snapshot }} {{ $line->base_unit_code_snapshot }} · revision {{ $line->revision }}</p></td><td class="px-4 py-3">{{ \App\Support\NumberFormatter::quantity($line->issuedQuantity()) }} {{ $line->unit_code_snapshot }}</td><td class="px-4 py-3"><input wire:model="lines.{{ $line->id }}.planned_quantity" type="number" step="any" class="w-32 rounded-lg border border-slate-200 px-3 py-2 dark:border-slate-700 dark:bg-navy-950"></td><td class="px-4 py-3"><input wire:model="lines.{{ $line->id }}.agreed_unit_price" type="number" step="0.01" class="w-40 rounded-lg border border-slate-200 px-3 py-2 dark:border-slate-700 dark:bg-navy-950"></td><td class="px-4 py-3 text-right font-bold">TZS {{ \App\Support\NumberFormatter::money((float)$lines[$line->id]['planned_quantity']*(float)$lines[$line->id]['agreed_unit_price']) }}</td><td class="px-4 py-3"><textarea wire:model="lines.{{ $line->id }}.amendment_reason" class="w-56 rounded-lg border border-slate-200 px-3 py-2 dark:border-slate-700 dark:bg-navy-950"></textarea>@error("lines.{$line->id}.amendment_reason")<p class="text-xs text-red-600">{{ $message }}</p>@enderror</td><td class="px-4 py-3"><button wire:click="saveLine({{ $line->id }})" class="rounded-lg bg-build-orange px-3 py-2 text-sm font-bold text-white">Save Line</button></td></tr>@endforeach</x-table></x-card>
</div>
