<?php
use App\Models\CustomerMaterialIssue;
use function Livewire\Volt\layout;
use function Livewire\Volt\mount;
use function Livewire\Volt\state;
layout('layouts.print');state(['materialIssue']);mount(function(CustomerMaterialIssue $materialIssue){$this->materialIssue=$materialIssue->load(['account.customer','account.company','lines.planLine','stockLocation','branch','issuedBy']);});
?>
<div class="mx-auto min-h-screen max-w-4xl bg-white p-8 text-slate-950">
    @php $issue=$materialIssue;$account=$issue->account;$money=fn($v)=>'TZS '.\App\Support\NumberFormatter::money($v); @endphp
    <div class="mb-8 flex justify-between border-b-2 border-slate-900 pb-5"><div><h1 class="text-2xl font-black">MATERIAL COLLECTION / ISSUE</h1><p>{{ $account->company?->company_name?:config('app.name') }}</p></div><button onclick="window.print()" class="print:hidden rounded-lg bg-slate-900 px-4 py-2 text-white">Print</button></div>
    <div class="mb-6 grid grid-cols-2 gap-4 text-sm md:grid-cols-4"><div><span class="text-slate-500">Reference</span><p class="font-bold">{{ $issue->reference_number }}</p></div><div><span class="text-slate-500">Date</span><p class="font-bold">{{ $issue->issued_at->format('d M Y H:i') }}</p></div><div><span class="text-slate-500">Customer</span><p class="font-bold">{{ $account->customer->name }}</p></div><div><span class="text-slate-500">Project Account</span><p class="font-bold">{{ $account->project_name }} · {{ $account->reference_number }}</p></div></div>
    <table class="w-full border-collapse text-sm"><thead><tr class="bg-slate-100"><th class="border p-3 text-left">Product</th><th class="border p-3 text-right">Quantity</th><th class="border p-3 text-right">Agreed Unit Price</th><th class="border p-3 text-right">Material Value</th><th class="border p-3 text-right">Remaining Planned Qty</th></tr></thead><tbody>@foreach($issue->lines as $line)<tr><td class="border p-3">{{ $line->product_name_snapshot }}</td><td class="border p-3 text-right">{{ \App\Support\NumberFormatter::quantity($line->quantity) }} {{ $line->unit_code_snapshot }}</td><td class="border p-3 text-right">{{ $money($line->agreed_unit_price) }}</td><td class="border p-3 text-right">{{ $money($line->line_value) }}</td><td class="border p-3 text-right">{{ \App\Support\NumberFormatter::quantity($line->planLine->remainingQuantity()) }} {{ $line->unit_code_snapshot }}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="3" class="border p-3 text-right">Total</th><th class="border p-3 text-right">{{ $money($issue->total_value) }}</th><td class="border"></td></tr></tfoot></table>
    <div class="mt-6 grid grid-cols-2 gap-4 text-sm md:grid-cols-4"><div><span class="text-slate-500">Remaining Funded Balance</span><p class="font-bold">{{ $money($account->availableFundedBalance()) }}</p></div><div><span class="text-slate-500">Stock Location</span><p class="font-bold">{{ $issue->stockLocation->name }}</p></div><div><span class="text-slate-500">Issued By</span><p class="font-bold">{{ $issue->issuedBy?->name??'-' }}</p></div><div><span class="text-slate-500">Collected By</span><p class="font-bold">{{ $issue->collected_by?:'-' }}</p></div></div>
    @if($issue->notes)<p class="mt-5"><strong>Notes:</strong> {{ $issue->notes }}</p>@endif
</div>
