<?php
use App\Models\CustomerMaterialAccount;
use App\Models\CustomerMaterialCashTransaction;
use App\Models\CustomerMaterialIssueLine;
use function Livewire\Volt\layout;
layout('layouts.app');
?>
<div>
    <x-page-header title="Customer Material Account Reports" description="Funded balances, deposits, issues, commitments, and project profitability." :breadcrumbs="['Dashboard'=>route('dashboard'),'Material Accounts'=>route('customer-material-accounts.index'),'Reports'=>null]" />
    @php $accounts=CustomerMaterialAccount::with(['customer','branch','planLines'])->latest()->get();$deposits=CustomerMaterialCashTransaction::with(['account.customer','branch','receivedBy'])->where('transaction_type','deposit')->latest('transacted_at')->limit(100)->get();$issueLines=CustomerMaterialIssueLine::with(['issue.account.customer','issue.stockLocation','issue.issuedBy'])->latest()->limit(100)->get();$money=fn($v)=>'TZS '.\App\Support\NumberFormatter::money($v); @endphp
    <div class="grid gap-4 md:grid-cols-3"><x-card><p class="text-sm text-slate-500">Total Unused Customer Funds</p><p class="text-xl font-black text-emerald-600">{{ $money($accounts->sum(fn($a)=>$a->availableFundedBalance())) }}</p></x-card><x-card><p class="text-sm text-slate-500">Outstanding Material Commitments</p><p class="text-xl font-black text-amber-600">{{ $money($accounts->sum(fn($a)=>$a->remainingProjectCommitment())) }}</p></x-card><x-card><p class="text-sm text-slate-500">Issued Gross Profit</p><p class="text-xl font-black">{{ $money($issueLines->sum('line_value')-$issueLines->sum('line_cost')) }}</p></x-card></div>
    <x-card class="mt-5" title="Customer Material Accounts"><x-table :headers="['Project / Customer','Project Value','Deposited','Issued','Available','Remaining Commitment','Status']">@foreach($accounts as $a)<tr><td class="px-4 py-3"><a wire:navigate class="font-bold text-build-orange" href="{{ route('customer-material-accounts.show',$a) }}">{{ $a->project_name }}</a><p class="text-xs text-slate-500">{{ $a->customer->name }} · {{ $a->reference_number }}</p></td><td class="px-4 py-3 text-right">{{ $money($a->plannedValue()) }}</td><td class="px-4 py-3 text-right">{{ $money($a->depositedAmount()) }}</td><td class="px-4 py-3 text-right">{{ $money($a->issuedValue()) }}</td><td class="px-4 py-3 text-right">{{ $money($a->availableFundedBalance()) }}</td><td class="px-4 py-3 text-right">{{ $money($a->remainingProjectCommitment()) }}</td><td class="px-4 py-3">{{ str($a->status)->title() }}</td></tr>@endforeach</x-table></x-card>
    <x-card class="mt-5" title="Customer Deposits"><x-table :headers="['Date','Customer','Project','Amount','Method','Reference','Branch','Received By']">@foreach($deposits as $d)<tr><td class="px-4 py-3">{{ $d->transacted_at->format('d M Y H:i') }}</td><td class="px-4 py-3">{{ $d->account->customer->name }}</td><td class="px-4 py-3">{{ $d->account->project_name }}</td><td class="px-4 py-3 text-right">{{ $money($d->amount) }}</td><td class="px-4 py-3">{{ str($d->payment_method)->replace('_',' ')->title() }}</td><td class="px-4 py-3">{{ $d->reference_number }}</td><td class="px-4 py-3">{{ $d->branch->name }}</td><td class="px-4 py-3">{{ $d->receivedBy?->name??'-' }}</td></tr>@endforeach</x-table></x-card>
    <x-card class="mt-5" title="Material Issues / Profitability"><x-table :headers="['Date','Customer / Project','Product','Quantity / Unit','Base Quantity','Revenue','COGS','Gross Profit','Location','Issued By']">@foreach($issueLines as $line)<tr><td class="px-4 py-3">{{ $line->issue->issued_at->format('d M Y') }}</td><td class="px-4 py-3">{{ $line->issue->account->customer->name }}<p class="text-xs text-slate-500">{{ $line->issue->account->project_name }}</p></td><td class="px-4 py-3">{{ $line->product_name_snapshot }}</td><td class="px-4 py-3">{{ \App\Support\NumberFormatter::quantity($line->quantity) }} {{ $line->unit_code_snapshot }}</td><td class="px-4 py-3">{{ \App\Support\NumberFormatter::quantity($line->base_quantity) }} {{ $line->base_unit_code_snapshot }}</td><td class="px-4 py-3 text-right">{{ $money($line->line_value) }}</td><td class="px-4 py-3 text-right">{{ $money($line->line_cost) }}</td><td class="px-4 py-3 text-right font-bold">{{ $money((float)$line->line_value-(float)$line->line_cost) }}</td><td class="px-4 py-3">{{ $line->issue->stockLocation->name }}</td><td class="px-4 py-3">{{ $line->issue->issuedBy?->name??'-' }}</td></tr>@endforeach</x-table></x-card>
    <x-card class="mt-5" title="Outstanding Material Commitments"><x-table :headers="['Customer / Project','Material','Planned','Issued','Remaining','Unit','Remaining Value']">@foreach($accounts as $a)@foreach($a->planLines->filter(fn($line)=>$line->remainingQuantity()>0) as $line)<tr><td class="px-4 py-3">{{ $a->customer->name }}<p class="text-xs text-slate-500">{{ $a->project_name }}</p></td><td class="px-4 py-3 font-bold">{{ $line->product_name_snapshot }}</td><td class="px-4 py-3 text-right">{{ \App\Support\NumberFormatter::quantity($line->planned_quantity) }}</td><td class="px-4 py-3 text-right">{{ \App\Support\NumberFormatter::quantity($line->issuedQuantity()) }}</td><td class="px-4 py-3 text-right font-black">{{ \App\Support\NumberFormatter::quantity($line->remainingQuantity()) }}</td><td class="px-4 py-3">{{ $line->unit_code_snapshot }}</td><td class="px-4 py-3 text-right">{{ $money($line->remainingQuantity()*(float)$line->agreed_unit_price) }}</td></tr>@endforeach @endforeach</x-table></x-card>
    <span class="sr-only">Project Profitability</span>
</div>
